### ISSUE TITLE
Calibration math wrong

### ISSUE THREAD

**Issue by presslab-us** [wemos/LOLIN_HP303B_Library#3]
https://github.com/wemos/LOLIN_HP303B_Library/blob/4deb5f568d4991abda28f716127946e6607bce6e/src/LOLIN_HP303B.cpp#L1341

This calculation is missing one term and will not correctly temperature compensate the pressure.  See the datasheet for the correct calculation.

**Comment by mike2nl** [comment]
@presslab-us 
the bad thing is that Wemos will never update his own libraries or will use any external PR.
I have done for so many libraries from Wemos and save them locally.

We could work together to get the most out of it. Beginning with the *.h file because missing things so far i have seen.
